# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7870bea37008fd315d433195cc87e446"
name = "ScriptInjector"
handle = "scriptinjectorapp"
application_url = "https://scriptinjector-app.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "scriptinjector.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes"

[auth]
redirect_urls = [
  "https://scriptinjector-app.onrender.com/auth/callback",
  "https://scriptinjector-app.onrender.com/auth/shopify/callback",
  "https://scriptinjector-app.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
